feat: add box select, box select with pointer, lasso select, lasso
featherity/featherity pull request #69
Opened 2020-09-06 04:03 UTC by llaenowyd

see also
llaenowyd/featherity:mishkaio_pr_57 - copy of #57
llaenowyd/featherity:mishkaio_pr_57_bullhorn_news_doc_lost_search - #57 minus these
llaenowyd/featherity:mishkaio_pr_57_lasso_box_select - #57 minus those

then this is a non-artistic rendition of the box selects with more spacing as was said on review of #57

@mishkaio I wanted to focus the PR while preserving the work, there my fork has a feature branch with the other part of it.  The review on #57 included something on those icons and I have no opinion on the suitability of the suggested alternatives.

@ericfennis I don't know from the discussion in the [feather issue 943](https://github.com/feathericons/feather/issues/943) if I was supposed to pick up and carry the ball from the PR #57, but since I could use these icons I tried to do just that, in a flexible way with these several feature branches.

Also I really have no idea about editing svg's.  I could see the lines for making space but the path for the cursor was really a stretch.  Then we have rectangles, etc..  The lasso ones, I didn't even try to think too hard about it.

All the existing icons are smaller in size and usually a single path element.  I tried applying svgo but it was more of a terser than a real simplification.

2020-09-06 04:15 UTC, mishkaio commented
@llaenowyd I'm not really clear on what I'm supposed to do now, if anything, or if you were just informing me. I have zero familiarity with this whole process, I was just trying to contribute as a designer. If still like to help, I just need clear directions.

2020-09-06 10:24 UTC, johnletey commented
@llaenowyd Thank you for taking the time to update @mishkaio's icons.

I think it's best if you commented on the original PR, #57, and @mishkaio can update them herself.

Again, thank you for taking the time 😄

2020-09-21 20:35 UTC, ericfennis commented
I reopened this issue, I don't get any response on #57 .
So @llaenowyd feel free to submit your versions.

2020-09-22 12:54 UTC, llaenowyd commented
> I reopened this issue, I don't get any response on #57 .
> So @llaenowyd feel free to submit your versions.

Ok. I'm completely busy through the end of this week.

I took a look at the other PR. I think the latest feedback is to try something more of a dashed-line rectangle.

What I might do is focus the change down to the selection rectangle.

Is the version with cursor semantically different or a stylistic option?

Unless I'm missing something about it, I might bring in the box-with-cursor as an alternative possibility for box-select, rather than a request for 2 icons for box-select.

2020-09-25 11:00 UTC, ericfennis commented
@llaenowyd No problem, take your time!

2020-09-26 13:26 UTC, llaenowyd commented
The latest review feedback was when @ericfennis said

> Btw we can also go more this way? ...
> ![image](https://user-images.githubusercontent.com/11825403/93124252-9eb8ec00-f6c9-11ea-910d-d5534e082ce1.png)

2020-09-26 13:43 UTC, llaenowyd commented
![dashed_line_square_grid](https://user-images.githubusercontent.com/41239783/94342112-c74fb880-ffdc-11ea-88f3-3ffb3df0087d.png)
![dashed_line_square_1_1](https://user-images.githubusercontent.com/41239783/94342115-c9197c00-ffdc-11ea-8929-1030ff627e26.png)

2020-09-26 16:52 UTC, ericfennis requested changes
@llaenowyd Nice work, looks awesome.
I think we can optimize the code a bit by replacing some line elements with polylines.

2020-09-26 16:52 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="2" y1="2" x2="4" y2="2"/>
```suggestion
  <polyline points="2 4 2 2 4 2" />
```

2020-09-26 16:52 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="22" y1="2" x2="22" y2="4"/>
```suggestion
  <polyline points="20 2 22 2 22 4" />
```

2020-09-26 16:52 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="20" y1="22" x2="22" y2="22"/>
```suggestion
  <polyline points="22 20 22 22 20 22" />
```

2020-09-26 16:52 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="2" y1="20" x2="2" y2="22"/>
```suggestion
  <polyline points="2 20 2 22 4 22" />
```

2020-09-27 20:22 UTC, ericfennis requested changes
@llaenowyd We always add an space before the end of the tag. Sorry I missed those.

2020-09-27 20:22 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="14" y1="2" x2="16" y2="2"/>
```suggestion
  <line x1="8" y1="2" x2="10" y2="2" />
  <line x1="14" y1="2" x2="16" y2="2" />
```

2020-09-27 20:22 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="22" y1="14" x2="22" y2="16"/>
```suggestion
  <line x1="22" y1="8" x2="22" y2="10" />
  <line x1="22" y1="14" x2="22" y2="16" />
```

2020-09-27 20:22 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="8" y1="22" x2="10" y2="22"/>
```suggestion
  <line x1="14" y1="22" x2="16" y2="22" />
  <line x1="8" y1="22" x2="10" y2="22" />
```

2020-09-27 20:22 UTC, ericfennis commented on icons/box-select.svg
> +  <line x1="2" y1="8" x2="2" y2="10"/>
```suggestion
  <line x1="2" y1="14" x2="2" y2="16" />
  <line x1="2" y1="8" x2="2" y2="10" />
```

2020-09-27 22:32 UTC, llaenowyd commented
np - missed that - updated

2020-09-28 17:01 UTC, ericfennis commented
I checked the guidelines, I think we forgot one thing. 
We have 2px rounded corners. 

What do you think? I think this looks better.  

![image](https://user-images.githubusercontent.com/11825403/94462470-da6caf00-01bb-11eb-9599-ab771ecab8f1.png)
100%
![image](https://user-images.githubusercontent.com/11825403/94462778-4cdd8f00-01bc-11eb-92e1-30e44b8f8bfe.png)

Here is the code
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M4 2a2 2 0 00-2 2" />
  <line x1="8" y1="2" x2="10" y2="2" />
  <line x1="14" y1="2" x2="16" y2="2" />
  <path d="M4 22a2 2 0 01-2-2" />
  <line x1="22" y1="8" x2="22" y2="10" />
  <line x1="22" y1="14" x2="22" y2="16" />
  <path d="M22 20a2 2 0 01-2 2" />
  <line x1="14" y1="22" x2="16" y2="22" />
  <line x1="8" y1="22" x2="10" y2="22" />
  <path d="M20 2a2 2 0 012 2" />
  <line x1="2" y1="14" x2="2" y2="16" />
  <line x1="2" y1="8" x2="2" y2="10" />
</svg>
```

2020-09-28 18:00 UTC, locness3 commented
Yup, rounded looks better.

2020-09-28 21:30 UTC, llaenowyd commented
same, looks good!

2020-09-28 21:48 UTC, ericfennis approved these changes

2020-09-28 21:57 UTC, llaenowyd commented
🎉 

I think I can consider this done for my part right?

What's the rough estimated timeline for it showing up in [npm feather-icons](https://www.npmjs.com/package/feather-icons)?

2020-09-29 06:42 UTC, ericfennis commented
@llaenowyd unfortunately maybe never.
The author of feather-icons stopped maintaining the feather-icons projects 😔.
Featherity is just an independent fork runned by the community some of people worked on Feather icons.
See this [thread](https://github.com/feathericons/feather/issues/893), how it all started.

2020-09-29 06:43 UTC, merged

2020-09-29 06:43 UTC, ericfennis commented
@llaenowyd But we are launching our own package soon!

2020-09-29 15:34 UTC, llaenowyd commented
Ok, I see, interesting. I've seen dead packages and live packages, but I've never watched what looks to be a well motivated community effort to resuscitate a package. Hope to see it land. 👍